# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
